from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c5ddf35e095c'
down_revision: Union[str, Sequence[str], None] = 'cdce3970432d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")